### ISSUE TITLE
Necessary improvements

### ISSUE THREAD

**Issue by HasanMajhali** [manishkatyan/bbb-analytics#6]
Hi , As Far I Know this is works for all Server Side meetings 
So Please Note this : 
1. Need to Add Login/Logout Button
2. Need to Add Auto Refresh so the New Meetings Data auto Appear  Without Applying "bbb-analytics --deploy" to Make it Appear
3. In UI No need to show (internal) meeting id under ClassName from end user point of view
4. End date is coming as 01/01/1970, 05:30:00 (epoch time).
5. For the meeting which does not have recording, the recording link should be hidden/disabled.

**Comment by arun-hel** [comment]
@HasanMajhali  Thanks for the feedback.

1. We already have login and once the session expires you will be logged out automatically.
2. We updated the npm package. Now page refresh will fetch all the latest analytics. please use the latest package. To install the latest package follow the below steps as a root user:
```bash
# Uninstall the old package.
npm uninstall -g bigbluebutton-analytics

# Remove node_modules 
rm -rf /usr/lib/node_modules/bigbluebutton-analytics

# Install the latest version
npm i -g bigbluebutton-analytics

# Regenrate the dashboard data
bbb-analytics --deploy

```
3. We will implement this in the next release.
4. Some sessions will have an `ended time  0` instead of a valid timestamp. That is causing the Incorrect` End Date`.
5. We are on it.

**Comment by HasanMajhali** [comment]
> 

Thank you for your Reply 

One more Thing :
* can it be implemented in Greenlight So each Room Admin user can view only the analytics for his/her meetings.

**Comment by arun-hel** [comment]
@HasanMajhali We have that feature implemented in greenlight. check it out at https://class.higheredlab.com/
